{{- if ne .Values.deploymentTarget "local" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Values.serverTier }}
spec:
  acme:
    # The ACME server URL
    {{ if eq .Values.serverTier "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    {{ if eq .Values.serverTier "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ end }}
    # Email address used for ACME registration
    email: {{ .Values.certManager.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.serverTier }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.class | default "nginx" }}
{{- else -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cinco-cloud-local-ca-cert
spec:
  isCA: true
  commonName: {{ .Values.ingress.host }}-local-rootCA
  dnsNames:
    - {{ .Values.ingress.host }}
  subject:
    organizations:
      - Cinco Cloud Local Development Org.
  secretName: cinco-cloud-local-ca-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cinco-cloud-local-ca-issuer
spec:
  ca:
    secretName: cinco-cloud-local-ca-cert-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cinco-cloud-local-development-cert
spec:
  isCA: false
  commonName: {{ .Values.ingress.host }}-local-development-cert
  dnsNames:
    - {{ .Values.ingress.host }}
  subject:
    organizations:
      - Cinco Cloud Local Development Org.
  secretName: cinco-cloud-local-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cinco-cloud-local-ca-issuer
    kind: Issuer
    group: cert-manager.io
{{ end }}